/*Copyright (c) 2016-2017 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

@TypeDefs({@TypeDef(name = "DateTime",
                     defaultForType = org.joda.time.LocalDateTime.class,
                     typeClass = com.wavemaker.commons.data.type.WMPersistentLocalDateTime.class)})
package com.guardian.sessiondb;

import org.hibernate.annotations.TypeDefs;
import org.hibernate.annotations.TypeDef;

