/*Copyright (c) 2016-2017 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.guardian.sessiondb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;

/**
 * SpringSessionAttributes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`SPRING_SESSION_ATTRIBUTES`")
@IdClass(SpringSessionAttributesId.class)
public class SpringSessionAttributes implements Serializable {

    private String sessionId;
    private String attributeName;
    private String attributeBytes;

    @Id
    @Column(name = "`SESSION_ID`", nullable = false, length = 36)
    public String getSessionId() {
        return this.sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    @Id
    @Column(name = "`ATTRIBUTE_NAME`", nullable = false, length = 200)
    public String getAttributeName() {
        return this.attributeName;
    }

    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    @Column(name = "`ATTRIBUTE_BYTES`", nullable = false, length = 2147483647)
    public String getAttributeBytes() {
        return this.attributeBytes;
    }

    public void setAttributeBytes(String attributeBytes) {
        this.attributeBytes = attributeBytes;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SpringSessionAttributes)) return false;
        final SpringSessionAttributes springSessionAttributes = (SpringSessionAttributes) o;
        return Objects.equals(getSessionId(), springSessionAttributes.getSessionId()) &&
                Objects.equals(getAttributeName(), springSessionAttributes.getAttributeName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getSessionId(),
                getAttributeName());
    }
}

