/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.guardian.sendemail.controller;

import com.guardian.sendemail.SendEmail;
import java.lang.String;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;

@RestController
@RequestMapping(value = "/sendEmail")
public class SendEmailController {

    @Autowired
    private SendEmail sendEmail;

    @RequestMapping(value = "/sendanemail", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "")
    public void sendanemail(@RequestParam(value = "Name", required = false) String Name, @RequestParam(value = "to", required = false) String to, @RequestParam(value = "eSubject", required = false) String eSubject, @RequestParam(value = "ebody", required = false) String ebody) {
        sendEmail.sendanemail(Name, to, eSubject, ebody);
    }
}
